# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: unified_diff 0.3.6 ruby lib

Gem::Specification.new do |s|
  s.name = "unified_diff"
  s.version = "0.3.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ryan Neufeld"]
  s.date = "2014-08-12"
  s.description = "unified_diff parses unified diff contents into easy-to-use Ruby objects"
  s.email = "ryan@ryanneufeld.ca"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/unified_diff.rb",
    "lib/unified_diff/chunk.rb",
    "lib/unified_diff/diff.rb",
    "test/helper.rb",
    "test/test_chunk.rb",
    "test/test_unified_diff.rb",
    "unified_diff.gemspec"
  ]
  s.homepage = "http://github.com/rkneufeld/unified_diff"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Parse unified diffs in style"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

